# Generated by Django 5.2.9 on 2026-01-08 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateTimeField(auto_now_add=True)),
                ('student_team_id', models.CharField(max_length=50, verbose_name='Student Team ID')),
                ('pmt_name', models.CharField(max_length=100, verbose_name='PMT Name')),
                ('district', models.CharField(max_length=100)),
                ('river_basin', models.CharField(max_length=100)),
                ('proposed_site_code', models.CharField(blank=True, help_text='EMC Format', max_length=50)),
                ('local_site_name', models.CharField(blank=True, max_length=200)),
                ('stream_name', models.CharField(max_length=200)),
                ('village_panchayat', models.CharField(max_length=200, verbose_name='Village / Panchayat')),
                ('nearest_landmark', models.CharField(blank=True, max_length=200)),
                ('intake_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Intake Lat')),
                ('intake_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Intake Long')),
                ('intake_elevation_m', models.FloatField(verbose_name='Intake Elevation (m)')),
                ('powerhouse_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='PH Lat')),
                ('powerhouse_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='PH Long')),
                ('powerhouse_elevation_m', models.FloatField(blank=True, null=True, verbose_name='PH Elevation (m)')),
                ('access_type', models.CharField(choices=[('Road', 'Road'), ('Footpath', 'Footpath'), ('River Crossing', 'River Crossing')], max_length=50)),
                ('distance_from_road_km', models.FloatField(verbose_name='Distance from road (km)')),
                ('seasonal_access_constraints', models.TextField(blank=True, help_text='Monsoon / landslide / forest restriction')),
                ('flow_type', models.CharField(choices=[('Perennial', 'Perennial'), ('Seasonal', 'Seasonal')], max_length=50)),
                ('qualitative_flow_desc', models.TextField(verbose_name='Qualitative Flow Description')),
                ('observed_flow_condition', models.CharField(choices=[('Lean', 'Lean'), ('Average', 'Average'), ('Flood', 'Flood')], max_length=50)),
                ('diversions_upstream', models.BooleanField(default=False, verbose_name='Any Diversions Upstream?')),
                ('measured_head_m', models.FloatField(verbose_name='Measured Head (m)')),
                ('dem_assisted_head_m', models.FloatField(blank=True, null=True, verbose_name='DEM-assisted Head (m)')),
                ('discharge_measured', models.BooleanField(default=False, verbose_name='Discharge Measurement Taken?')),
                ('measured_discharge_lps', models.FloatField(blank=True, null=True, verbose_name='Measured Discharge (lps)')),
                ('measurement_method', models.CharField(blank=True, choices=[('Float', 'Float'), ('Bucket', 'Bucket'), ('Visual Estimate', 'Visual Estimate')], max_length=50)),
                ('season_of_measurement', models.CharField(blank=True, choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Aug', 'Aug'), ('Sep', 'Sep'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], max_length=20)),
                ('land_ownership', models.CharField(choices=[('Forest', 'Forest'), ('Private', 'Private'), ('Estate', 'Estate'), ('Temple', 'Temple'), ('Govt', 'Govt')], max_length=50)),
                ('forest_boundary_within_500m', models.BooleanField(default=False)),
                ('known_clearances_needed', models.TextField(blank=True)),
                ('nearby_wildlife', models.BooleanField(default=False, verbose_name='Nearby Wildlife Presence')),
                ('waterfall_within_500m', models.BooleanField(default=False)),
                ('tribal_settlement_nearby', models.BooleanField(default=False)),
                ('existing_water_uses', models.CharField(help_text='Irrigation, Drinking, Tourism, etc.', max_length=255)),
                ('social_sensitivities', models.TextField(blank=True)),
                ('nearest_kseb_line_km', models.FloatField(verbose_name='Nearest KSEB Line Distance (km)')),
                ('voltage_level', models.CharField(choices=[('LT', 'LT'), ('11kV', '11kV'), ('33kV', '33kV')], max_length=20)),
                ('nearest_substation', models.CharField(max_length=100)),
                ('indicative_capacity_kw', models.FloatField(verbose_name='Indicative Installed Capacity (kW)')),
                ('basis_of_estimate', models.CharField(choices=[('Thumb rule', 'Thumb rule'), ('PMT guidance', 'PMT guidance')], max_length=50)),
                ('tentative_plf', models.FloatField(blank=True, null=True, verbose_name='Tentative PLF')),
                ('nearby_gauge_station', models.CharField(blank=True, max_length=100, verbose_name='Nearby CWC/KSEB Gauge')),
                ('correlation_method', models.CharField(choices=[('Area ratio', 'Area ratio'), ('Regional', 'Regional')], max_length=50)),
                ('confidence_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('photo_intake', models.ImageField(upload_to='photos/intake/', verbose_name='Intake Location Photo')),
                ('photo_powerhouse', models.ImageField(upload_to='photos/powerhouse/', verbose_name='Powerhouse Location Photo')),
                ('photo_upstream', models.ImageField(upload_to='photos/upstream/', verbose_name='Stream Upstream Photo')),
                ('photo_access', models.ImageField(upload_to='photos/access/', verbose_name='Access Route Photo')),
                ('overall_feasibility', models.CharField(choices=[('Promising', 'Promising'), ('Uncertain', 'Uncertain'), ('Not promising', 'Not promising')], max_length=50)),
                ('key_constraints', models.TextField()),
                ('recommend_tier_1', models.BooleanField(default=False, verbose_name='Recommend for Tier-1 Study')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
