# Generated by Django 5.2.9 on 2026-01-06 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('river_stream_name', models.CharField(max_length=200)),
                ('site_type', models.CharField(choices=[('River', 'River'), ('Canal', 'Canal'), ('Dam Toe', 'Dam Toe')], max_length=50)),
                ('installed_capacity_mw', models.DecimalField(decimal_places=2, help_text='In MW', max_digits=10)),
                ('type_of_turbine', models.CharField(max_length=100)),
                ('avg_annual_rainfall_mm', models.FloatField(help_text='In mm')),
                ('avg_discharge', models.FloatField(help_text='m3/s')),
                ('generator_capacity_mw', models.DecimalField(decimal_places=2, help_text='In MW', max_digits=10)),
                ('annual_energy_production', models.FloatField(help_text='Units in MU or kWh')),
                ('current_status', models.CharField(choices=[('Proposed', 'Proposed'), ('Under Construction', 'Under Construction'), ('Operational', 'Operational')], max_length=50)),
                ('is_rejected', models.BooleanField(default=False)),
                ('reason_for_rejection', models.TextField(blank=True, null=True)),
                ('fr_report', models.FileField(blank=True, null=True, upload_to='fr_reports/', verbose_name='Feasibility Report (FR)')),
                ('special_study_report', models.FileField(blank=True, null=True, upload_to='special_studies/')),
                ('env_clearance_doc', models.FileField(blank=True, null=True, upload_to='env_docs/', verbose_name='Environmental Clearance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
